feat: added navigation bar
kir-dev/schpincer-frontend pull request #10
Opened 2024-06-09 11:47 UTC by Var3sz

2024-06-09 13:00 UTC, berenteb requested changes

2024-06-09 13:00 UTC, berenteb commented on src/components/navbar/navbar.tsx
> +'use client';
Ide egyelőre nem kell use client, később jól jöhet

2024-06-09 13:00 UTC, berenteb commented on src/components/navbar/navbar.tsx
> +  ];
Ezt általában célszerű kimozgatni a függvényen kívülre, hogy ne jöjjön létre renderek között

2024-06-09 13:00 UTC, berenteb commented on src/app/layout.tsx
> +        <div>
Ez a div felesleges itt, enélkül is jól lesz. Kivéve ha stílusozzuk majd, de akkor inkább a body-n tegyük ezt.

2024-06-10 18:35 UTC, Var3sz commented on src/components/navbar/navbar.tsx
> +'use client';
Kis felbontású képernyő támogatásához kellett useState, úgyhogy ez maradt így.

2024-06-16 14:54 UTC, berenteb approved these changes

2024-06-16 16:04 UTC, merged